services:
  - type: web
    name: pdf-extraction-api
    env: python
    buildCommand: pip install -r app/requirements.txt
    startCommand: cd app && PYTHONPATH=$PYTHONPATH:. uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 