services:
  - type: web
    name: pdf-extraction-api
    env: python
    buildCommand: pip install -e .
    startCommand: PYTHONPATH=/opt/render/project/src uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src 